version: '3.9'

networks:
  treenet:
    driver: bridge

services:
    tree:
        image: 'docker-spring-boot:latest'
        build:
          context: .
          dockerfile: Dockerfile
        ports:
            - "8081:8080"
        depends_on:
          neo4j-tree:
            condition: service_healthy
        links:
            - neo4j-tree
        networks:
        - treenet
        container_name: tree
        environment:
          - SPRING_NEO4J_URI=neo4j://neo4j-tree:7687
          - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
          - SPRING_NEO4J_AUTHENTICATION_PASSWORD=P@ssw0rd
    neo4j-tree:
        image: "neo4j:latest"
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
          NEO4J_AUTH: "neo4j/P@ssw0rd"
        networks:
        - treenet
        container_name: neo4j-tree
        healthcheck:
            test: cypher-shell --username neo4j --password P@ssw0rd 'MATCH (n) RETURN COUNT(n);'
            interval: 10s
            timeout: 10s
            retries: 5